name: Report a bug
description: Let us know if an extension is not working as intended
body:
  - type: markdown
    attributes:
      value: |
        Hi, thank you for taking the time to create an issue! Before you get started, please ensure the following are correct:

        - I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
        - There's [no other issue](https://github.com/directus-labs/extensions/issues?q=is%3Aissue) that already describes the problem.

        _For issues specific to the core project, please [submit issues](https://github.com/directus/directus/issues/new/choose) at the [official GitHub organisation for Directus](https://github.com/directus)._
  - type: dropdown
    id: extension
    attributes:
      label: Extension
      description: Which extension does this issue relate to?
      options:
        - Address Completion Interface
        - AI Alt Text Writer Operation
        - AI Focal Point Detection Operation
        - AI Image Generation Operation
        - AI Image Moderation Operation
        - AI Researcher Bundle
        - AI Speech Generation Operation
        - AI Text Extraction Operation
        - AI Text Intelligence Operation
        - AI Transcription Operation
        - AI Translator Operation
        - AI Web Scraper Operation
        - AI Writer Operation
        - Algolia Operation
        - API Metric Panel
        - Audio Player Interface
        - Calculated Fields Bundle
        - Card Select Interfaces
        - Choropleth Map Panel
        - Command Palette Module
        - Display Link Interface
        - Elasticsearch Operation
        - Experimental M2A Interface
        - Field Comments
        - Flow Trigger Bundle
        - Funnel Chart Panel
        - Gantt Chart Layout
        - GitHub Operation
        - Hubspot Operation
        - Inline Repeater Interface
        - Input Rich Text HTML File Link
        - Liquidjs Operation
        - Meilisearch Operation
        - Extension Meter Component
        - Migration Bundle
        - Multilevel Autocomplete API Interface
        - Opensearch Operation
        - PDF Viewer Interface
        - Plausible Analytics Bundle
        - Related Items Bundle
        - Resend Operation
        - Rss to JSON Operation
        - Scatter Plot Panel
        - SEO Plugin
        - Simple List Interface
        - Spreadsheet Layout
        - Extension Steps Component
        - Switch Interface
        - Table View Panel
        - Timeline Chart Panel
        - Tour Group Interface
        - Tree View Table Layout
        - Treemap Chart Panel
        - Video Player Interface
        - Whereby Embedded Interface
        - Whiteboard Interface
        - YouTube Embed Interface
        - Something else
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description:
        Steps to reproduce the behavior. Contributors should be able to follow the steps provided in order to reproduce
        the bug.
    validations:
      required: true
  - type: input
    attributes:
      label: Directus Version
      placeholder: v10.x.x
    validations:
      required: true
  - type: dropdown
    id: deployment
    attributes:
      label: Hosting Strategy
      options:
        - Self-Hosted (Docker Image)
        - Self-Hosted (Custom)
        - Directus Cloud
    validations:
      required: true
