export default [
	{ value: 'AR', text: 'Arabic' },
	{ value: 'BG', text: 'Bulgarian' },
	{ value: 'CS', text: 'Czech' },
	{ value: 'DA', text: 'Danish' },
	{ value: 'DE', text: 'German' },
	{ value: 'EL', text: 'Greek' },
	{ value: 'EN-GB', text: 'English (British)' },
	{ value: 'EN-US', text: 'English (American)' },
	{ value: 'ES', text: 'Spanish' },
	{ value: 'ET', text: 'Estonian' },
	{ value: 'FI', text: 'Finnish' },
	{ value: 'FR', text: 'French' },
	{ value: 'HU', text: 'Hungarian' },
	{ value: 'ID', text: 'Indonesian' },
	{ value: 'IT', text: 'Italian' },
	{ value: 'JA', text: 'Japanese' },
	{ value: 'KO', text: 'Korean' },
	{ value: 'LT', text: 'Lithuanian' },
	{ value: 'LV', text: 'Latvian' },
	{ value: 'NB', text: 'Norwegian (Bokmål)' },
	{ value: 'NL', text: 'Dutch' },
	{ value: 'PL', text: 'Polish' },
	{ value: 'PT-BR', text: 'Portuguese (Brazilian)' },
	{ value: 'PT-PT', text: 'Portuguese' },
	{ value: 'RO', text: 'Romanian' },
	{ value: 'RU', text: 'Russian' },
	{ value: 'SK', text: 'Slovak' },
	{ value: 'SL', text: 'Slovenian' },
	{ value: 'SV', text: 'Swedish' },
	{ value: 'TR', text: 'Turkish' },
	{ value: 'UK', text: 'Ukrainian' },
	{ value: 'ZH', text: 'Chinese (simplified)' },
];
